# Site settings
title: luchigster
name: luchigster
url: "http://luchigster.github.io/"
email: luchigster@gmail.com
description: luchigster的博客
baseurl: "" # the subpath of your site, e.g. /blog/
qq_username: 335987347  # QQ ID
twitter_username: chiguang  # Twitter ID
github_username:  luchigster # Github ID
weibo_username: 1649582600  # Weibo ID
facebook_username: luchigster  # Facebook ID
duoshuo_username: luchigster # Duoshuo ID
baidushare_id: 89860593 #  百度分享 ID
baidutongji_id: 47edf05fd16d9dc154a5163b4314265b # 百度统计 ID
#google-analytics_id: UA-50593531-1  # Google Analytics ID
rss_url: "/feed.xml"  # RSS 订阅 URL
logo_image: "/images/cnm.jpg"  # LOGO 图片地址
# Build settings
gems: [jekyll-paginate]
highlighter: rouge
permalink: /:title/
paginate: 8
paginate_path: page/:num
 